dist: xenial

language: python

python:
  - "3.9"

cache: pip

install:
  - pip install -r test_requirements.txt
  - pip install -e .

script:
  - ruff check .
  - black --check .
  - pytest

branches:
  only:
    - main
