dist: xenial

language: python

python:
  - "3.8"

cache: pip

install:
  - pip install -r test_requirements.txt
  - pip install -e .

script:
  - flake8
  - pytest
  - black --check .

branches:
  only:
    - main
